// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MODELO.contexto;


#nullable disable

namespace ModeloIds.Migrations
{
    [DbContext(typeof(Estacionamiento))]
    [Migration("20250306195039_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("int");

                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("int");

                    b.HasKey("AccionesACC_ID", "GruposGRU_ID");

                    b.HasIndex("GruposGRU_ID");

                    b.ToTable("AccionGrupo");
                });

            modelBuilder.Entity("AccionUsuario", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosPER_ID")
                        .HasColumnType("int");

                    b.HasKey("AccionesACC_ID", "UsuariosPER_ID");

                    b.HasIndex("UsuariosPER_ID");

                    b.ToTable("AccionUsuario");
                });

            modelBuilder.Entity("EspacioTipoVehiculo", b =>
                {
                    b.Property<int>("EspaciosEspacioId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculosTipoVehiculoId")
                        .HasColumnType("int");

                    b.HasKey("EspaciosEspacioId", "VehiculosTipoVehiculoId");

                    b.HasIndex("VehiculosTipoVehiculoId");

                    b.ToTable("EspacioTipoVehiculo");
                });

            modelBuilder.Entity("GrupoUsuario", b =>
                {
                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosPER_ID")
                        .HasColumnType("int");

                    b.HasKey("GruposGRU_ID", "UsuariosPER_ID");

                    b.HasIndex("UsuariosPER_ID");

                    b.ToTable("GrupoUsuario");
                });

            modelBuilder.Entity("MODELO.Clases.Descuento", b =>
                {
                    b.Property<int>("DescuentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescuentoId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreDescuento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DescuentoId");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("MODELO.Clases.MetodoDePago", b =>
                {
                    b.Property<int>("MetodoDePagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoDePagoId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreMetodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MetodoDePagoId");

                    b.ToTable("Metodos_Pagos");
                });

            modelBuilder.Entity("MODELO.Clases.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime>("FechaHoraPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoDePagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TicketBaseId")
                        .HasColumnType("int");

                    b.HasKey("PagoId");

                    b.HasIndex("MetodoDePagoId");

                    b.HasIndex("TicketBaseId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("MODELO.Clases.TipoVehiculo", b =>
                {
                    b.Property<int>("TipoVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoVehiculoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoVehiculoId");

                    b.ToTable("Tipos_Vehiculos");
                });

            modelBuilder.Entity("MODELO.Tarifa", b =>
                {
                    b.Property<int>("TarifaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarifaId"));

                    b.Property<DateTime>("FechaHoraActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioDia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioMediaHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioMes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("int");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("TarifaId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("MODELO.TicketBase", b =>
                {
                    b.Property<int>("TicketBaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketBaseId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspacioId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TarifaId")
                        .HasColumnType("int");

                    b.HasKey("TicketBaseId");

                    b.HasIndex("EspacioId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TarifaId");

                    b.ToTable("Tickets_Base");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TicketBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Modelo_Ids.Espacio", b =>
                {
                    b.Property<int>("EspacioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspacioId"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<bool>("EsMenusal")
                        .HasColumnType("bit");

                    b.Property<string>("NombreEspacio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspacioId");

                    b.ToTable("Espacios");
                });

            modelBuilder.Entity("Modelo_Ids.Estado_Ticket", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoId");

                    b.ToTable("Estados_Tickets");
                });

            modelBuilder.Entity("seg2.Accion", b =>
                {
                    b.Property<int>("ACC_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ACC_ID"));

                    b.Property<string>("ACC_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("FOR_ID")
                        .HasColumnType("int");

                    b.HasKey("ACC_ID");

                    b.HasIndex("FOR_ID");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("seg2.Estado_Grupo", b =>
                {
                    b.Property<int>("EST_GRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EST_GRU_ID"));

                    b.Property<string>("EST_GRU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("EST_GRU_ID");

                    b.ToTable("Estados_Grupos");
                });

            modelBuilder.Entity("seg2.Estado_Usuario", b =>
                {
                    b.Property<int>("EST_USU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EST_USU_ID"));

                    b.Property<string>("EST_USU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("EST_USU_ID");

                    b.ToTable("Estados_Usuarios");
                });

            modelBuilder.Entity("seg2.Formulario", b =>
                {
                    b.Property<int>("FOR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FOR_ID"));

                    b.Property<string>("FOR_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("MOD_ID")
                        .HasColumnType("int");

                    b.HasKey("FOR_ID");

                    b.HasIndex("MOD_ID");

                    b.ToTable("Formularios");
                });

            modelBuilder.Entity("seg2.Grupo", b =>
                {
                    b.Property<int>("GRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GRU_ID"));

                    b.Property<int>("EST_GRU_ID")
                        .HasColumnType("int");

                    b.Property<string>("GRU_DESCRIPCION")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("GRU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("GRU_ID");

                    b.HasIndex("EST_GRU_ID");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("seg2.Modulo", b =>
                {
                    b.Property<int>("MOD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MOD_ID"));

                    b.Property<string>("MOD_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MOD_ID");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("seg2.Persona", b =>
                {
                    b.Property<int>("PER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PER_ID"));

                    b.Property<string>("PER_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("PER_ID");

                    b.ToTable("Personas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MODELO.Clases.Cuota", b =>
                {
                    b.HasBaseType("MODELO.TicketBase");

                    b.Property<bool>("Actual")
                        .HasColumnType("bit");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasIndex("PlanId");

                    b.HasDiscriminator().HasValue("Cuota");
                });

            modelBuilder.Entity("MODELO.Clases.Ticket", b =>
                {
                    b.HasBaseType("MODELO.TicketBase");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Ticket");
                });

            modelBuilder.Entity("MODELO.Clases.Plan", b =>
                {
                    b.HasBaseType("seg2.Persona");

                    b.Property<int?>("DescuentoId")
                        .HasColumnType("int");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoPlan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.HasIndex("DescuentoId");

                    b.ToTable("Planes", (string)null);
                });

            modelBuilder.Entity("seg2.Usuario", b =>
                {
                    b.HasBaseType("seg2.Persona");

                    b.Property<int?>("EST_USU_ID")
                        .HasColumnType("int");

                    b.Property<string>("USU_CLAVE")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("USU_MAIL")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("USU_USUARIO")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasIndex("EST_USU_ID");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.HasOne("seg2.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("seg2.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccionUsuario", b =>
                {
                    b.HasOne("seg2.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("seg2.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosPER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EspacioTipoVehiculo", b =>
                {
                    b.HasOne("Modelo_Ids.Espacio", null)
                        .WithMany()
                        .HasForeignKey("EspaciosEspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.Clases.TipoVehiculo", null)
                        .WithMany()
                        .HasForeignKey("VehiculosTipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoUsuario", b =>
                {
                    b.HasOne("seg2.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("seg2.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosPER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MODELO.Clases.Pago", b =>
                {
                    b.HasOne("MODELO.Clases.MetodoDePago", "MetodoDePago")
                        .WithMany()
                        .HasForeignKey("MetodoDePagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.TicketBase", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoDePago");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MODELO.Tarifa", b =>
                {
                    b.HasOne("MODELO.Clases.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("MODELO.TicketBase", b =>
                {
                    b.HasOne("Modelo_Ids.Espacio", "Espacio")
                        .WithMany("Tickets")
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo_Ids.Estado_Ticket", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.Tarifa", "Tarifa")
                        .WithMany()
                        .HasForeignKey("TarifaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espacio");

                    b.Navigation("Estado");

                    b.Navigation("Tarifa");
                });

            modelBuilder.Entity("seg2.Accion", b =>
                {
                    b.HasOne("seg2.Formulario", "Formulario")
                        .WithMany("Acciones")
                        .HasForeignKey("FOR_ID");

                    b.Navigation("Formulario");
                });

            modelBuilder.Entity("seg2.Formulario", b =>
                {
                    b.HasOne("seg2.Modulo", "Modulo")
                        .WithMany("Formularios")
                        .HasForeignKey("MOD_ID");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("seg2.Grupo", b =>
                {
                    b.HasOne("seg2.Estado_Grupo", "Estado_Grupo")
                        .WithMany()
                        .HasForeignKey("EST_GRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado_Grupo");
                });

            modelBuilder.Entity("MODELO.Clases.Cuota", b =>
                {
                    b.HasOne("MODELO.Clases.Plan", "Plan")
                        .WithMany("Cuotas")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MODELO.Clases.Plan", b =>
                {
                    b.HasOne("MODELO.Clases.Descuento", "Descuento")
                        .WithMany()
                        .HasForeignKey("DescuentoId");

                    b.HasOne("seg2.Persona", null)
                        .WithOne()
                        .HasForeignKey("MODELO.Clases.Plan", "PER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descuento");
                });

            modelBuilder.Entity("seg2.Usuario", b =>
                {
                    b.HasOne("seg2.Estado_Usuario", "Estado_Usuario")
                        .WithMany()
                        .HasForeignKey("EST_USU_ID");

                    b.HasOne("seg2.Persona", null)
                        .WithOne()
                        .HasForeignKey("seg2.Usuario", "PER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado_Usuario");
                });

            modelBuilder.Entity("Modelo_Ids.Espacio", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("seg2.Formulario", b =>
                {
                    b.Navigation("Acciones");
                });

            modelBuilder.Entity("seg2.Modulo", b =>
                {
                    b.Navigation("Formularios");
                });

            modelBuilder.Entity("MODELO.Clases.Plan", b =>
                {
                    b.Navigation("Cuotas");
                });
#pragma warning restore 612, 618
        }
    }
}
