// <auto-generated />
using System;
using MODELO.contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ModeloIds.Migrations
{
    [DbContext(typeof(Estacionamiento))]
    [Migration("20260219143009_valorNuevoNullable")]
    partial class valorNuevoNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("int");

                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("int");

                    b.HasKey("AccionesACC_ID", "GruposGRU_ID");

                    b.HasIndex("GruposGRU_ID");

                    b.ToTable("AccionGrupo");
                });

            modelBuilder.Entity("AccionUsuario", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosPER_ID")
                        .HasColumnType("int");

                    b.HasKey("AccionesACC_ID", "UsuariosPER_ID");

                    b.HasIndex("UsuariosPER_ID");

                    b.ToTable("AccionUsuario");
                });

            modelBuilder.Entity("EspacioTipoVehiculo", b =>
                {
                    b.Property<int>("EspaciosEspacioId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculosTipoVehiculoId")
                        .HasColumnType("int");

                    b.HasKey("EspaciosEspacioId", "VehiculosTipoVehiculoId");

                    b.HasIndex("VehiculosTipoVehiculoId");

                    b.ToTable("EspacioTipoVehiculo");
                });

            modelBuilder.Entity("GrupoUsuario", b =>
                {
                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosPER_ID")
                        .HasColumnType("int");

                    b.HasKey("GruposGRU_ID", "UsuariosPER_ID");

                    b.HasIndex("UsuariosPER_ID");

                    b.ToTable("GrupoUsuario");
                });

            modelBuilder.Entity("MODELO.AuditoriaTicket", b =>
                {
                    b.Property<int>("AuditoriaTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaTicketId"));

                    b.Property<string>("CampoModificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketBaseId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditoriaTicketId");

                    b.HasIndex("TicketBaseId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaTickets");
                });

            modelBuilder.Entity("MODELO.Descuento", b =>
                {
                    b.Property<int>("DescuentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescuentoId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreDescuento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DescuentoId");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("MODELO.Espacio", b =>
                {
                    b.Property<int>("EspacioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspacioId"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<bool>("EsMenusal")
                        .HasColumnType("bit");

                    b.Property<string>("NombreEspacio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspacioId");

                    b.ToTable("Espacios");
                });

            modelBuilder.Entity("MODELO.Estado_Ticket", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoId");

                    b.ToTable("Estados_Tickets");
                });

            modelBuilder.Entity("MODELO.MetodoDePago", b =>
                {
                    b.Property<int>("MetodoDePagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoDePagoId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreMetodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MetodoDePagoId");

                    b.ToTable("Metodos_Pagos");
                });

            modelBuilder.Entity("MODELO.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime>("FechaHoraPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoDePagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoEstacionamiento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoServicios")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TicketBaseId")
                        .HasColumnType("int");

                    b.HasKey("PagoId");

                    b.HasIndex("MetodoDePagoId");

                    b.HasIndex("TicketBaseId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("MODELO.TarifaEstacionamiento", b =>
                {
                    b.Property<int>("TarifaEstacionamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarifaEstacionamientoId"));

                    b.Property<DateTime>("FechaHoraActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioDia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioMediaHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioMes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("int");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("TarifaEstacionamientoId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("Tarifas_Estacionamiento");
                });

            modelBuilder.Entity("MODELO.TarifaServicio", b =>
                {
                    b.Property<int>("TarifaServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarifaServicioId"));

                    b.Property<DateTime>("FechaHoraActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServicioVehiculoId")
                        .HasColumnType("int");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("TarifaServicioId");

                    b.HasIndex("ServicioVehiculoId");

                    b.ToTable("Tarifa_Servicios");
                });

            modelBuilder.Entity("MODELO.TicketBase", b =>
                {
                    b.Property<int>("TicketBaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketBaseId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspacioId")
                        .HasColumnType("int");

                    b.Property<bool>("EstacionamientoPago")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TarifaEstacionamientoId")
                        .HasColumnType("int");

                    b.Property<int>("TarifaId")
                        .HasColumnType("int");

                    b.HasKey("TicketBaseId");

                    b.HasIndex("EspacioId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TarifaEstacionamientoId");

                    b.ToTable("Tickets_Base");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TicketBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MODELO.TipoServicio", b =>
                {
                    b.Property<int>("TipoServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoServicioId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("TipoServicioId");

                    b.ToTable("Tipo_Servicios");
                });

            modelBuilder.Entity("MODELO.TipoVehiculo", b =>
                {
                    b.Property<int>("TipoVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoVehiculoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoVehiculoId");

                    b.ToTable("Tipos_Vehiculos");
                });

            modelBuilder.Entity("MODELO.seguridad.Accion", b =>
                {
                    b.Property<int>("ACC_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ACC_ID"));

                    b.Property<string>("ACC_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("FOR_ID")
                        .HasColumnType("int");

                    b.HasKey("ACC_ID");

                    b.HasIndex("FOR_ID");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("MODELO.seguridad.AuditoriaSesion", b =>
                {
                    b.Property<int>("AuditoriaSesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaSesionId"));

                    b.Property<string>("EstadoSesion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHoraLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraLogout")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SesionActiva")
                        .HasColumnType("bit");

                    b.Property<int?>("TiempoInactividad")
                        .HasColumnType("int");

                    b.Property<string>("TipoLogout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("AuditoriaSesionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaSesiones");
                });

            modelBuilder.Entity("MODELO.seguridad.Estado_Grupo", b =>
                {
                    b.Property<int>("EST_GRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EST_GRU_ID"));

                    b.Property<string>("EST_GRU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("EST_GRU_ID");

                    b.ToTable("Estados_Grupos");
                });

            modelBuilder.Entity("MODELO.seguridad.Estado_Usuario", b =>
                {
                    b.Property<int>("EST_USU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EST_USU_ID"));

                    b.Property<string>("EST_USU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("EST_USU_ID");

                    b.ToTable("Estados_Usuarios");
                });

            modelBuilder.Entity("MODELO.seguridad.Formulario", b =>
                {
                    b.Property<int>("FOR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FOR_ID"));

                    b.Property<string>("FOR_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("MOD_ID")
                        .HasColumnType("int");

                    b.HasKey("FOR_ID");

                    b.HasIndex("MOD_ID");

                    b.ToTable("Formularios");
                });

            modelBuilder.Entity("MODELO.seguridad.Grupo", b =>
                {
                    b.Property<int>("GRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GRU_ID"));

                    b.Property<int>("EST_GRU_ID")
                        .HasColumnType("int");

                    b.Property<string>("GRU_DESCRIPCION")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("GRU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("GRU_ID");

                    b.HasIndex("EST_GRU_ID");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("MODELO.seguridad.Modulo", b =>
                {
                    b.Property<int>("MOD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MOD_ID"));

                    b.Property<string>("MOD_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MOD_ID");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("MODELO.seguridad.Persona", b =>
                {
                    b.Property<int>("PER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PER_ID"));

                    b.Property<string>("PER_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("PER_ID");

                    b.ToTable("Personas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Modelo_Ids.PagoDetalle", b =>
                {
                    b.Property<int>("PagoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoDetalleId"));

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioConsumidoId")
                        .HasColumnType("int");

                    b.HasKey("PagoDetalleId");

                    b.HasIndex("PagoId");

                    b.HasIndex("ServicioConsumidoId");

                    b.ToTable("PagoDetalles");
                });

            modelBuilder.Entity("Modelo_Ids.ServicioConsumido", b =>
                {
                    b.Property<int>("ServicioConsumidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioConsumidoId"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraAsignado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<int?>("PlanPER_ID")
                        .HasColumnType("int");

                    b.Property<int>("TarifaServicioId")
                        .HasColumnType("int");

                    b.Property<int>("TicketBaseId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketDiarioTicketBaseId")
                        .HasColumnType("int");

                    b.HasKey("ServicioConsumidoId");

                    b.HasIndex("PlanPER_ID");

                    b.HasIndex("TarifaServicioId");

                    b.HasIndex("TicketDiarioTicketBaseId");

                    b.ToTable("ServiciosConsumidos");
                });

            modelBuilder.Entity("Modelo_Ids.ServicioVehiculo", b =>
                {
                    b.Property<int>("ServicioVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioVehiculoId"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<double>("TiempoEstimado")
                        .HasColumnType("float");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("int");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("int");

                    b.HasKey("ServicioVehiculoId");

                    b.HasIndex("TipoVehiculoId");

                    b.HasIndex("TipoServicioId", "ServicioVehiculoId")
                        .IsUnique();

                    b.ToTable("ServiciosVehiculos");
                });

            modelBuilder.Entity("MODELO.Cuota", b =>
                {
                    b.HasBaseType("MODELO.TicketBase");

                    b.Property<bool>("Actual")
                        .HasColumnType("bit");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasIndex("PlanId");

                    b.HasDiscriminator().HasValue("Cuota");
                });

            modelBuilder.Entity("MODELO.Ticket_Diario", b =>
                {
                    b.HasBaseType("MODELO.TicketBase");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Ticket_Diario");
                });

            modelBuilder.Entity("MODELO.Plan", b =>
                {
                    b.HasBaseType("MODELO.seguridad.Persona");

                    b.Property<int?>("DescuentoId")
                        .HasColumnType("int");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoPlan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.HasIndex("DescuentoId");

                    b.ToTable("Planes", (string)null);
                });

            modelBuilder.Entity("MODELO.seguridad.Usuario", b =>
                {
                    b.HasBaseType("MODELO.seguridad.Persona");

                    b.Property<int?>("EST_USU_ID")
                        .HasColumnType("int");

                    b.Property<string>("USU_CLAVE")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("USU_MAIL")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("USU_USUARIO")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasIndex("EST_USU_ID");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.HasOne("MODELO.seguridad.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.seguridad.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccionUsuario", b =>
                {
                    b.HasOne("MODELO.seguridad.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosPER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EspacioTipoVehiculo", b =>
                {
                    b.HasOne("MODELO.Espacio", null)
                        .WithMany()
                        .HasForeignKey("EspaciosEspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.TipoVehiculo", null)
                        .WithMany()
                        .HasForeignKey("VehiculosTipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoUsuario", b =>
                {
                    b.HasOne("MODELO.seguridad.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosPER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MODELO.AuditoriaTicket", b =>
                {
                    b.HasOne("MODELO.TicketBase", "Ticket")
                        .WithMany("auditoriaTickets")
                        .HasForeignKey("TicketBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.seguridad.Usuario", "Usuario")
                        .WithMany("AuditoriaTickets")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MODELO.Pago", b =>
                {
                    b.HasOne("MODELO.MetodoDePago", "MetodoDePago")
                        .WithMany()
                        .HasForeignKey("MetodoDePagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.TicketBase", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketBaseId");

                    b.Navigation("MetodoDePago");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MODELO.TarifaEstacionamiento", b =>
                {
                    b.HasOne("MODELO.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("MODELO.TarifaServicio", b =>
                {
                    b.HasOne("Modelo_Ids.ServicioVehiculo", "ServicioVehiculo")
                        .WithMany("Tarifas")
                        .HasForeignKey("ServicioVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicioVehiculo");
                });

            modelBuilder.Entity("MODELO.TicketBase", b =>
                {
                    b.HasOne("MODELO.Espacio", "Espacio")
                        .WithMany("Tickets")
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.Estado_Ticket", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.TarifaEstacionamiento", "TarifaEstacionamiento")
                        .WithMany()
                        .HasForeignKey("TarifaEstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espacio");

                    b.Navigation("Estado");

                    b.Navigation("TarifaEstacionamiento");
                });

            modelBuilder.Entity("MODELO.seguridad.Accion", b =>
                {
                    b.HasOne("MODELO.seguridad.Formulario", "Formulario")
                        .WithMany("Acciones")
                        .HasForeignKey("FOR_ID");

                    b.Navigation("Formulario");
                });

            modelBuilder.Entity("MODELO.seguridad.AuditoriaSesion", b =>
                {
                    b.HasOne("MODELO.seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MODELO.seguridad.Formulario", b =>
                {
                    b.HasOne("MODELO.seguridad.Modulo", "Modulo")
                        .WithMany("Formularios")
                        .HasForeignKey("MOD_ID");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("MODELO.seguridad.Grupo", b =>
                {
                    b.HasOne("MODELO.seguridad.Estado_Grupo", "Estado_Grupo")
                        .WithMany()
                        .HasForeignKey("EST_GRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado_Grupo");
                });

            modelBuilder.Entity("Modelo_Ids.PagoDetalle", b =>
                {
                    b.HasOne("MODELO.Pago", "Pago")
                        .WithMany("PagoDetalles")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo_Ids.ServicioConsumido", "ServicioConsumido")
                        .WithMany()
                        .HasForeignKey("ServicioConsumidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");

                    b.Navigation("ServicioConsumido");
                });

            modelBuilder.Entity("Modelo_Ids.ServicioConsumido", b =>
                {
                    b.HasOne("MODELO.Plan", "Plan")
                        .WithMany("ServiciosConsumidos")
                        .HasForeignKey("PlanPER_ID");

                    b.HasOne("MODELO.TarifaServicio", "TarifaServicio")
                        .WithMany()
                        .HasForeignKey("TarifaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.Ticket_Diario", "TicketDiario")
                        .WithMany("ServiciosConsumidos")
                        .HasForeignKey("TicketDiarioTicketBaseId");

                    b.Navigation("Plan");

                    b.Navigation("TarifaServicio");

                    b.Navigation("TicketDiario");
                });

            modelBuilder.Entity("Modelo_Ids.ServicioVehiculo", b =>
                {
                    b.HasOne("MODELO.TipoServicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.TipoVehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MODELO.Cuota", b =>
                {
                    b.HasOne("MODELO.Plan", "Plan")
                        .WithMany("Cuotas")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MODELO.Plan", b =>
                {
                    b.HasOne("MODELO.Descuento", "Descuento")
                        .WithMany()
                        .HasForeignKey("DescuentoId");

                    b.HasOne("MODELO.seguridad.Persona", null)
                        .WithOne()
                        .HasForeignKey("MODELO.Plan", "PER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descuento");
                });

            modelBuilder.Entity("MODELO.seguridad.Usuario", b =>
                {
                    b.HasOne("MODELO.seguridad.Estado_Usuario", "Estado_Usuario")
                        .WithMany()
                        .HasForeignKey("EST_USU_ID");

                    b.HasOne("MODELO.seguridad.Persona", null)
                        .WithOne()
                        .HasForeignKey("MODELO.seguridad.Usuario", "PER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado_Usuario");
                });

            modelBuilder.Entity("MODELO.Espacio", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MODELO.Pago", b =>
                {
                    b.Navigation("PagoDetalles");
                });

            modelBuilder.Entity("MODELO.TicketBase", b =>
                {
                    b.Navigation("auditoriaTickets");
                });

            modelBuilder.Entity("MODELO.seguridad.Formulario", b =>
                {
                    b.Navigation("Acciones");
                });

            modelBuilder.Entity("MODELO.seguridad.Modulo", b =>
                {
                    b.Navigation("Formularios");
                });

            modelBuilder.Entity("Modelo_Ids.ServicioVehiculo", b =>
                {
                    b.Navigation("Tarifas");
                });

            modelBuilder.Entity("MODELO.Ticket_Diario", b =>
                {
                    b.Navigation("ServiciosConsumidos");
                });

            modelBuilder.Entity("MODELO.Plan", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("ServiciosConsumidos");
                });

            modelBuilder.Entity("MODELO.seguridad.Usuario", b =>
                {
                    b.Navigation("AuditoriaTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
